In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Date    : May-19-23 18:25
# @Author  : Kan HUANG (kan.huang@connect.ust.hk)

import os
import numpy as np
import torch
import torch.nn.functional as F

In [2]:
target_codes = np.asarray([[0., 1., 0., 1., 1.],
               [0., 1., 1., 0., 1.],
               [0., 1., 1., 1., 0.],
               [1., 0., 0., 1., 1.],
               [1., 0., 1., 0., 1.],
               [1., 0., 1., 1., 0.],
               [1., 1., 0., 0., 1.],
               [1., 1., 0., 1., 0.],
               [1., 1., 1., 0., 0.],
               [0., 0., 1., 1., 1.],
               [0., 1., 0., 1., 1.],
               [0., 1., 1., 0., 1.],
               [0., 1., 1., 1., 0.],
               [1., 0., 0., 1., 1.],
               [1., 0., 1., 0., 1.],
               [1., 0., 1., 1., 0.]])
target_codes = torch.from_numpy(target_codes)

In [3]:
# 16 x 5
output = np.asarray([[-2.5099,  1.7667, -3.7351,  1.9043,  1.6348],
        [-1.0646,  0.7772,  0.2445, -1.3976,  0.4623],
        [-0.3707,  0.5058,  0.4578,  0.2354, -2.2048],
        [ 2.1191, -3.5932, -3.0759,  2.2187,  1.5929],
        [ 1.1155, -2.9434,  1.8652, -2.9491,  1.5238],
        [ 1.4766, -3.3255,  1.7521,  1.7163, -2.2792],
        [ 1.6706,  2.0003, -1.6131, -3.4864,  1.6853],
        [ 0.7880,  0.5957, -1.1589,  0.7183, -2.1697],
        [ 0.8532,  0.6800,  1.0857, -0.9564, -1.5706],
        [-1.0329, -2.5878,  0.6344,  0.5535,  0.4525],
        [-3.1936,  1.9788, -3.6889,  1.8114,  1.6479],
        [-4.2443,  1.9574,  2.3783, -2.9731,  1.8163],
        [-2.8714,  1.0121,  1.4761,  1.2548, -2.4620],
        [ 1.5615, -2.7669, -2.5947,  1.6095,  1.0280],
        [ 0.6863, -1.8052,  0.9909, -1.6921,  0.7287],
        [ 1.3614, -3.3797,  1.6767,  1.8689, -2.1003]])
output = torch.from_numpy(output)

import torch.nn.functional as F

output_softmax = F.softmax(output, dim=1)
output_softmax


tensor([[0.0046, 0.3287, 0.0013, 0.3772, 0.2881],
        [0.0612, 0.3862, 0.2267, 0.0439, 0.2819],
        [0.1301, 0.3126, 0.2980, 0.2385, 0.0208],
        [0.3698, 0.0012, 0.0021, 0.4085, 0.2185],
        [0.2148, 0.0037, 0.4546, 0.0037, 0.3231],
        [0.2763, 0.0023, 0.3639, 0.3511, 0.0065],
        [0.2900, 0.4032, 0.0109, 0.0017, 0.2943],
        [0.3387, 0.2795, 0.0483, 0.3159, 0.0176],
        [0.2981, 0.2507, 0.3761, 0.0488, 0.0264],
        [0.0632, 0.0134, 0.3351, 0.3090, 0.2793],
        [0.0022, 0.3886, 0.0013, 0.3287, 0.2791],
        [0.0006, 0.2940, 0.4479, 0.0021, 0.2553],
        [0.0053, 0.2553, 0.4061, 0.3255, 0.0079],
        [0.3753, 0.0049, 0.0059, 0.3937, 0.2201],
        [0.2797, 0.0232, 0.3793, 0.0259, 0.2918],
        [0.2456, 0.0021, 0.3366, 0.4079, 0.0077]], dtype=torch.float64)

In [4]:
result_softmax = torch.as_tensor((output_softmax - 0.5) > 0, dtype=torch.int32)
result_softmax


tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [5]:
distances = torch.zeros(len(output), len(target_codes))

for i, _output in enumerate(output):
    for j, target_code in enumerate(target_codes):
        distances[i][j] = F.l1_loss(_output, target_code)
pred = distances.argmax(dim=1, keepdim=True)
print(pred)
# correct += pred.eq(target.view_as(pred)).sum().item()

tensor([[4],
        [5],
        [3],
        [1],
        [0],
        [0],
        [2],
        [1],
        [0],
        [6],
        [4],
        [3],
        [3],
        [1],
        [7],
        [0]])


In [6]:
labels = torch.tensor([1, 4, 1, 0, 5, 2])
labels = labels.unsqueeze(0)
target = torch.zeros(labels.size(0), 15).scatter_(1, labels, 1.)
print(target)

tensor([[1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [7]:
target.shape

torch.Size([1, 15])

In [8]:
import torch.nn as nn
m = nn.Sigmoid()
loss_fn = nn.BCELoss()
input = torch.randn(3, 8, requires_grad=True)
target = torch.empty(3, 8).random_(2)
output = m(input)
loss = loss_fn(output, target)
loss.backward()

In [10]:
import json
from lenet import LeNet5

output_dir = "../output/ECOC-LeNet-5_MNIST_sgd_20230520-020335"
with open(f"{output_dir}/config.json") as f:
   args = json.load(f)
use_cuda = not args["no_cuda"] and torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
model = LeNet5(padding=2, output_dim=5).to(device)

In [11]:
model.load_state_dict(torch.load(f"{output_dir}/ECOC-LeNet-5.pt"))

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

In [12]:
from torchvision import datasets, transforms

kwargs = {'batch_size': args["batch_size"]}
if use_cuda:
    torch.cuda.manual_seed(args["seed"])
    kwargs.update({'num_workers': 1,
                    'pin_memory': True,
                    'shuffle': True},
                    )
print("Normalize MNIST input.")
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])
mnist_train = datasets.MNIST(os.path.expanduser(
    "~/.datasets"), train=True, download=True, transform=transform)
mnist_test = datasets.MNIST(os.path.expanduser(
    "~/.datasets"), train=False, transform=transform)
train_loader = torch.utils.data.DataLoader(mnist_train, **kwargs)
test_loader = torch.utils.data.DataLoader(mnist_test, **kwargs)

Normalize MNIST input.


In [13]:
data, target = next(iter(train_loader))
data, target = data.to(device), target.to(device)

In [45]:
import sys
sys.path.append("..")
from ecoc.encode import read_codebook, get_codebook_tensor

codebook_name = args["codebook_name"]
codebook_file = f"../ecoc/codebooks/{codebook_name}.csv"
codebook = read_codebook(codebook_file)
codebook_tensor = get_codebook_tensor(codebook).to(device)

In [46]:
codebook_tensor

tensor([[0., 0., 1., 1., 1.],
        [0., 1., 0., 1., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 1., 0.],
        [1., 0., 0., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 1., 0.],
        [1., 1., 0., 0., 1.],
        [1., 1., 0., 1., 0.],
        [1., 1., 1., 0., 0.]], device='cuda:0')

In [50]:
# Batch ECOC encoding
target_code = torch.zeros(len(data), 5).to(device)
for i, c in enumerate(target):
    target_code[i] += codebook_tensor[c]
target_code

tensor([[0., 1., 1., 0., 1.],
        [1., 1., 1., 0., 0.],
        [1., 1., 0., 0., 1.],
        [0., 1., 1., 0., 1.],
        [1., 0., 0., 1., 1.],
        [1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 1., 0., 1., 0.],
        [1., 1., 0., 1., 0.],
        [1., 0., 0., 1., 1.],
        [0., 1., 1., 0., 1.],
        [1., 1., 0., 0., 1.],
        [1., 1., 0., 0., 1.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 0., 1., 1.],
        [0., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1.],
        [0., 1., 1., 0., 1.],
        [1., 1., 0., 0., 1.],
        [0., 0., 1., 1., 1.],
        [0., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 0., 1., 1.],
        [0., 1., 0., 1., 1.],
        [1., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0.]], device='cuda:0')

In [51]:
output_code = torch.sigmoid(model(data))

In [52]:
output_code

tensor([[2.7461e-04, 9.9919e-01, 9.9995e-01, 5.3192e-05, 9.9999e-01],
        [9.0802e-01, 9.7821e-01, 8.6991e-01, 7.3043e-02, 3.3803e-01],
        [8.1087e-01, 9.9901e-01, 1.2846e-01, 3.0486e-02, 9.9635e-01],
        [4.9451e-03, 9.9571e-01, 9.9864e-01, 2.9050e-01, 9.5692e-01],
        [9.8374e-01, 1.7587e-03, 2.1061e-03, 9.9610e-01, 9.9981e-01],
        [9.9938e-01, 9.9832e-01, 9.9981e-01, 1.5633e-03, 8.6092e-05],
        [6.4486e-04, 1.7133e-05, 9.9998e-01, 9.9966e-01, 9.9958e-01],
        [9.9966e-01, 9.7709e-01, 3.9838e-02, 8.1712e-03, 9.5563e-01],
        [9.9955e-01, 5.3606e-04, 9.9902e-01, 5.0300e-04, 9.9970e-01],
        [9.9998e-01, 9.8730e-01, 1.3803e-04, 9.9734e-01, 1.5907e-02],
        [9.8861e-01, 9.9701e-01, 2.7495e-02, 9.4742e-01, 2.6049e-02],
        [9.8513e-01, 5.6772e-02, 5.6491e-02, 9.7225e-01, 9.8223e-01],
        [1.1108e-03, 9.9980e-01, 9.9864e-01, 2.2509e-02, 9.9026e-01],
        [9.9988e-01, 9.9988e-01, 2.6610e-04, 9.6002e-05, 9.9978e-01],
        [9.9122e-01,

In [61]:
loss_fn = nn.BCELoss(reduction="none")
loss_mat = loss_fn(output_code, target_code)

In [64]:
import math
def bce(a, b):
    return -(b*math.log(a)+(1-b)*math.log(1-a))

In [66]:
i, j = 1, 1
print(output_code[i][j])
print(target_code[i][j])
print(loss_mat[i][j])

tensor(0.9782, device='cuda:0', grad_fn=<SelectBackward0>)
tensor(1., device='cuda:0')
tensor(0.0220, device='cuda:0', grad_fn=<SelectBackward0>)


In [67]:
print(bce(output_code[i][j], target_code[i][j]))

tensor(0.0220, device='cuda:0')


In [88]:
result = torch.as_tensor((output_code - 0.5) > 0, dtype=torch.int32) 

distances = torch.zeros(len(result), len(codebook_tensor))
for i, _result in enumerate(result):
    for j, _code in enumerate(codebook_tensor):
        distances[i][j] = (_result-_code).abs().sum()
pred = distances.argmin(dim=1, keepdim=True).to(device)
correct = pred.eq(target.view_as(pred)).sum().item()

In [91]:
correct

32

In [81]:
result[0]

tensor([0, 1, 1, 0, 1], device='cuda:0', dtype=torch.int32)

In [83]:
codebook_tensor[2]

tensor([0., 1., 1., 0., 1.], device='cuda:0')

In [87]:
F.l1_loss(result[0], codebook_tensor[0])

tensor(0, device='cuda:0', dtype=torch.int32)